export const metadata = {
  title: "Contacts Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>Contact page me swagat he{children}</body>
    </html>
  );
}
